---
sudo: false
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef install JSON::Fast
before_script:
  - git clone https://github.com/exercism/problem-specifications.git
  - bin/fetch-configlet
script:
  - bin/configlet lint .
  - prove
    --exec perl6
    --recurse
    --jobs 2
